language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master; TYPE=coverage
      php: 5.3
    - env: DBTYPE=sqlite; MW=master; TYPE=composer
      php: 5.3
    - env: DBTYPE=mysql; MW=1.19.0; TYPE=relbuild; INFO=SEGFAULT
      php: 5.6
    - env: DBTYPE=sqlite; MW=1.19.0; INFO=SEGFAULT
      php: 5.5
    - env: DBTYPE=postgres; MW=1.19.0
      php: 5.4
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    # Since the build update, http://blog.travis-ci.com/2014-04-28-upcoming-build-environment-updates/
    # those fail with a segfault before install and testing
    - env: DBTYPE=mysql; MW=1.19.0; TYPE=relbuild; INFO=SEGFAULT
    - env: DBTYPE=sqlite; MW=1.19.0; INFO=SEGFAULT

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always
