language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.3
    - env: DBTYPE=mysql; MW=1.19.0
      php: 5.4
    - env: DBTYPE=mysql; MW=1.21.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=master
      php: 5.4
    - env: DBTYPE=sqlite; MW=1.19.0
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash .travis.setup.sh

script: cd ../phase3/tests/phpunit ; php phpunit.php --group SMWExtension -c ../../extensions/SemanticMediaWiki/phpunit.xml.dist

after_script: cd ../../extensions/SemanticMediaWiki ; bash .travis.coverage.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: never
    on_failure: always
