language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.3
    - env: DBTYPE=mysql; MW=1.19.0
      php: 5.4
    - env: DBTYPE=mysql; MW=1.21.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=master
      php: 5.4
    - env: DBTYPE=sqlite; MW=1.19.0
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL

before_script: bash .travis.setup.sh

script: bash .travis.test.sh

after_success:
  - cd ../phase3/extensions/SemanticMediaWiki
  - composer require satooshi/php-coveralls:dev-master
  - php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always
