language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.3
    - env: DBTYPE=mysql; MW=1.19.0
      php: 5.4
    - env: DBTYPE=mysql; MW=1.21.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=master
      php: 5.4
    - env: DBTYPE=sqlite; MW=1.19.0
      php: 5.5
    - env: DBTYPE=postgres; MW=master
      php: 5.5
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DBTYPE=postgres; MW=master

before_script:
  - bash .travis.sh

script:
  - cd ../phase3/tests/phpunit ; php phpunit.php --group SMWExtension --coverage-clover ../../extensions/SemanticMediaWiki/build/logs/clover.xml

after_script:
  - cd ../../extensions/SemanticMediaWiki
  - composer require satooshi/php-coveralls:dev-master
  - php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always